version: '2.1'
services:
  app:
    image: 'guardless/farm_help:latest'
    ports:
      - '8181:8181'
    container_name: cont_farm_help
    depends_on:
      database:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres'
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  database:
    image: 'postgres:13.1-alpine'
    container_name: database_farm_help
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - 'database-data:/var/lib/postgresql/data/'
volumes:
  database-data: null
